### ISSUE TITLE
Provide option to read password from environment variable

### ISSUE THREAD

**Issue by hanswurscht** [HurricaneLabs/splunksecrets#6]
First of all: Thank you for this great script! It helps us a lot in automating splunk deployment!

My feature request:
It would be easier for us to use in an automated fashion, if the script would be able to read the password from an environment variable. The new option could be named `--password-env`.

Currently only cli agruments and stdin are supported for password. Cli arguments are insecure, and stdin is kind of messy.

Thanks!

**Comment by mcm** [comment]
Hi @hanswurscht !

Thanks for your feedback. I've just released splunksecrets 0.5.0 which adds support for the following:

* Instead of `--splunk-secret`, you can set the `SPLUNK_SECRET` environment variable
* Instead of `--splunk-secret-text`, you can set the `SPLUNK_SECRET_TEXT` environment variable
* Instead of `--password`, you can set the `PASSWORD` environment variable

I know that's not exactly what you asked for, but it allowed me to add consistent behavior to all 3 options without a ton of extra processing logistics. Let me know if that works for you!

**Comment by hanswurscht** [comment]
Hi, that's perfect now,
Thanks again!

Btw: I had to make some changes to get this running under RHEL7 with default python2: I removed `import pcrypt` (and support for pre Splunk 7.2) and `six.ensure_binary.` `pcrypt` is only available in pip, and `six` is too old to support ensure_binary.
